### ISSUE TITLE
Cards link to the wrong place

### ISSUE THREAD

**Issue by marcoceppi** [CanonicalLtd/juju-cards#10]
_From @buggtb on March 3, 2016 15:9_

For example:
http://www.meteoriteconsulting.com/spinning-up-pentaho-data-integrations-quickly-with-juju/

If you click the link it goes to:
https://jujucharms.com/pentahodataintegration/trusty/0

not: 
https://jujucharms.com/u/f-tom-n/pentahodataintegration/trusty/0

_Copied from original issue: CanonicalLtd/jujucharms.com#216_

**Comment by marcoceppi** [comment]
@anthonydillon

**Comment by anthonydillon** [comment]
Thanks @marcoceppi, I'll be fixing up and releasing a new version with this fix tomorrow.

**Comment by anthonydillon** [comment]
This has been fixed with https://github.com/CanonicalLtd/juju-cards/commit/089facb7a81b4723b1b0044dc56d89f215f8f7ec
