### ISSUE TITLE
card styling awkward on a default Ghost blog

### ISSUE THREAD

**Issue by adam-stokes** [CanonicalLtd/juju-cards#11]
Using default ghost blog 0.7.8 and it's casper theme embedding a juju-card looks like this:

![image](https://cloud.githubusercontent.com/assets/51892/13678600/89369060-e6bd-11e5-8e8d-d62b5d28aca0.png)

I'm not sure where the conflict is happening but I'd be happy to give you access to my blog if you wanted to test the draft.

**Comment by anthonydillon** [comment]
Adam, I can't cant seem to replicate this issue. (http://codepen.io/anthonydillon/pen/YqWaaV). I wonder if some of the blog styling is effecting the card styles. If I could see the page I will investigate further.

**Comment by adam-stokes** [comment]
Here is the link to the draft page: http://blog.astokes.org/p/393de731-9808-4fb3-901e-9fa82c38de30/

**Comment by anthonydillon** [comment]
Thanks, its the post styling setting the images to be centred. I will reset the image styles in the card so it works for you.

**Comment by adam-stokes** [comment]
@anthonydillon awesome thanks!

**Comment by anthonydillon** [comment]
This will be fixed with version v1.1.0.

**Comment by adam-stokes** [comment]
Just tested with 1.1.0 and looks great!
![image](https://cloud.githubusercontent.com/assets/51892/13707793/5b7eeb1a-e779-11e5-9494-83f7a0fd14ca.png)
