### ISSUE TITLE
add a copy-to-clipboard button

### ISSUE THREAD

**Issue by adam-stokes** [CanonicalLtd/juju-cards#12]
Copying the embed code is a little involved and it would be nice to be able to just click a button to copy the embed code to my clipboard

**Comment by hatched** [comment]
This could be enabled for browsers that support the js copy-to-clipboard but not for ones that would require an additional library.

**Comment by mitechie** [comment]
Could we not do the same thing we do for the deploy command on
jujucharms.com?

**Comment by anthonydillon** [comment]
I agree. I'll add js copy to clipboard if supported by browser. No flash
here.

**Comment by anthonydillon** [comment]
This will be fixed with version v1.1.0.
