### ISSUE TITLE
Cards do not work when JS is striped out

### ISSUE THREAD

**Issue by anthonydillon** [CanonicalLtd/juju-cards#13]
It would be nice to show juju cards in places such as GitHub readme's but JS is not executed.

**Comment by brenopolanski** [comment]
Maybe create an extension to chrome/FF/opera and inject JS in background?

For example, the user put in README.md in your GitHub:

```
<juju-card name="saikuanalytics"></juju-card>
```

The extension will inject JS in page of GitHub and find the element `<juju-card>`, then change tags to the card of Saiku Analytics.

make sense to you?

If you need the some help, I can help you :)
