### ISSUE TITLE
Add ability to embed cards in Markdown (specifically GitHub)

### ISSUE THREAD

**Issue by adam-stokes** [CanonicalLtd/juju-cards#16]
I think it would be cool to be able to embed these cards in the README's for charms hosted on github. For example, I host my charm reactive code here https://github.com/battlemidget/juju-bundle-ghost this would be another way to get interested users over to the juju platform.

Another option if not able to embed the script code is to have some sort of badge that could represent something similar, for example, I see these badges everywhere:

![image](https://cloud.githubusercontent.com/assets/51892/13765621/5520b220-ea31-11e5-9298-72121196cbc2.png)

**Comment by anthonydillon** [comment]
Thanks @battlemidget I have this planned in for future development https://github.com/CanonicalLtd/juju-cards/issues/13. Your badges comment is very good. I will look into a solution.
