### ISSUE TITLE
Display bundles w/o images

### ISSUE THREAD

**Issue by buggtb** [CanonicalLtd/juju-cards#18]
Some times it might be preferable to display bundle cards but not include the image.

**Comment by anthonydillon** [comment]
@buggtb Thank you very much. I will think about the best way to pass that to the renderer and will get back to you.

**Comment by anthonydillon** [comment]
The reason this project was derived was to help provide a consistent look of promo across the web. By allowing methods to change to components. We will lose this consistency.
